[workspace]
channels = ["conda-forge"]
platforms = ["linux-64", "win-64", "osx-arm64"]
preview = ["pixi-build"]

[package]
name = "xdggs"
version = "9999.0.0"

[package.build]
backend = { name = "pixi-build-python", version = "0.*", channels = [
  "conda-forge",
] }
config = { noarch = true }

[package.host-dependencies]
python = "*"
hatchling = "*"
hatch-vcs = "*"

[package.run-dependencies]
python = ">=3.11"
xarray = ">=2025.08.0"
numpy = ">=2.2"
h3ronpy = ">=0.22.0"
lonboard = ">=0.14.0"
healpix-geo = ">=0.2.1"
arro3-core = "*"
pyproj = "*"
pooch = "*"
h5netcdf = "*"
matplotlib-base = ">=3.10.5"

[tasks]

[dependencies]
xdggs = { path = "." }
cdshealpix = ">=0.7.1"

[feature.tests.dependencies]
pytest = "*"
pytest-cov = "*"
pytest-xdist = "*"
netcdf4 = "*"
hypothesis = "*"
geoarrow-pyarrow = "*"
shapely = ">=2.1.1,<3"
dask = ">=2025.7.0"

[feature.tests.tasks]
tests = { cmd = "pytest -n auto --cov=xdggs", cwd = ".", default-environment = "default" }

[feature.ci-py311.dependencies]
python = "3.11.*"

[feature.ci-py312.dependencies]
python = "3.12.*"

[feature.ci-py313.dependencies]
python = "3.13.*"

[feature.docs.dependencies]
python = "3.13.*"
sphinx = "<9"
myst-nb = "*"
sphinx-book-theme = "*"
sphinx-autosummary-accessors = "*"
sphinx-copybutton = "*"
sphinx-design = "*"
sphinx-inline-tabs = "*"
sphinxcontrib-bibtex = "*"
h5netcdf = "*"
pooch = "*"
shapely = ">=2.1.1"
sphinx-autobuild = ">=2024.10.3"
jupyter-sphinx = ">=0.5.3,<0.6"

[feature.docs.tasks]
build-docs = { cmd = "rm -rf generated/; python -m sphinx -b html -w warnings.log -W -Tn -j auto . _build", cwd = "docs" }
autobuild-docs = { cmd = "sphinx-autobuild -b html -w warnings.log -W -Tn -j auto . _build", cwd = "docs" }
build-docs-rtd = { cmd = "python -m sphinx -b html -W -T -j auto . $READTHEDOCS_OUTPUT/html", cwd = "docs" }

[feature.dev.dependencies]
python = "3.13.*"
ipython = "*"
black = "*"
isort = "*"
jupyterlab = "*"
jupyter-resource-usage = "*"
jupyterlab_code_formatter = "*"
python-build = ">=1.3.0"
h3-py = ">=4.3.0"
geopandas = ">=1.1.1"
pyinstrument = ">=5.1.1"
jupyterlab-myst = ">=2.4.2"
h5netcdf = ">=1.7.3"
zarr = ">=3.1.5"
cf-xarray = ">=0.11.1"

[feature.ci.dependencies]
python = "*"

[feature.ci.tasks]
nightly-tests = { cmd = "pixi run --manifest-path ci/nightly/pixi.toml tests", cwd = "." }

[environments]
ci-py311 = { features = ["tests", "ci-py311"] }
ci-py312 = { features = ["tests", "ci-py312"] }
ci-py313 = { features = ["tests", "ci-py313"] }
docs = { features = ["docs"] }
default = { features = ["tests", "dev"] }
ci = { features = ["ci"], no-default-feature = true }
