[workspace]
channels = ["conda-forge"]
platforms = ["linux-64"]

[dependencies]
python = "3.14.*"
pyproj = "*"
arro3-core = "*"
matplotlib-base = "*"
rust = "*"
pytest-reportlog = "*"
pooch = "*"

[pypi-options.dependency-overrides]
numpy = { version = "*", index = "https://pypi.anaconda.org/scientific-python-nightly-wheels/simple" }
pandas = { version = "*", index = "https://pypi.anaconda.org/scientific-python-nightly-wheels/simple" }
xarray = { version = "*", index = "https://pypi.anaconda.org/scientific-python-nightly-wheels/simple" }
pyarrow = { version = "*", index = "https://pypi.anaconda.org/scientific-python-nightly-wheels/simple" }

[pypi-dependencies]
xdggs = { path = "../..", editable = true }
xarray = "*"
numpy = "*"
pandas = "*"
pyarrow = "*"
h3ronpy = { git = "git+https://github.com/nmandery/h3ronpy.git", subdirectory = "h3ronpy" }
cdshealpix = { git = "git+https://github.com/cds-astro/cds-healpix-python.git" }
healpix-geo = { git = "git+https://github.com/eopf-dggs/healpix-geo.git", subdirectory = "python/healpix-geo" }
astropy = { git = "git+https://github.com/astropy/astropy.git" }
lonboard = { git = "git+https://github.com/developmentseed/lonboard.git" }

[feature.tests.dependencies]
pytest = "*"
pytest-cov = "*"
pytest-xdist = "*"
hypothesis = "*"
geoarrow-pyarrow = "*"
shapely = ">=2.1.1,<3"
dask = ">=2025.7.0"

[feature.tests.tasks]
tests = { cmd = "pytest -n 0 auto --cov=xdggs", cwd = "../.." }


[environments]
nightly = ["tests"]
